#!/bin/bash
# write-env.sh - validate and write .qualcomm-env.
#
# Reads KEY=VALUE lines on stdin, validates them, writes atomically, then
# VERIFIES the permissions rather than assuming chmod worked (it silently does
# nothing on a Windows filesystem).
#
#   bash write-env.sh <<'ENV'
#   QC_TOPOLOGY=B
#   QC_BUILD_HOST=user@host
#   QC_BOARD_ACCESS=none
#   ENV
#
# Env:
#   OUT   target path (default: ./.qualcomm-env)

set -euo pipefail

OUT="${OUT:-$(pwd)/.qualcomm-env}"
TMP="${OUT}.tmp.$$"
SCHEMA=1

die()  { echo "ERROR: $*" >&2; rm -f "$TMP"; exit 1; }
warn() { echo "WARNING: $*" >&2; }

# Keys that must never be persisted. A password belongs in the SSH agent or an
# environment variable supplied at run time, not in a config file that gets
# copied between machines and pasted into issues.
SECRET_RE='(PASS|PASSWD|PASSWORD|SECRET|TOKEN|APIKEY|API_KEY|PRIVATE_KEY|CREDENTIAL)'

VALID_TOPOLOGY='^[ABCD]$'
VALID_ACCESS='^(ssh-key|ssh-password|ssh-jump|adb|serial|none)$'

declare -a LINES=()
topology="" access="" board="" build=""

while IFS= read -r line || [ -n "$line" ]; do
    [ -z "${line// }" ] && continue
    case "$line" in \#*) LINES+=("$line"); continue ;; esac
    case "$line" in *=*) ;; *) die "not KEY=VALUE: $line" ;; esac

    key="${line%%=*}"
    val="${line#*=}"

    # --- refuse credentials outright ---
    if printf '%s' "$key" | grep -qiE "$SECRET_RE"; then
        die "refusing to write credential-shaped key '$key'.
       Record the ACCESS METHOD instead and supply the secret at run time
       (ssh-agent, ~/.ssh/config, or an environment variable)."
    fi
    # A key= that looks like an inline password in a host string
    if printf '%s' "$val" | grep -qE '://[^/@]*:[^/@]*@'; then
        die "value for '$key' embeds credentials in a URL. Remove them."
    fi

    case "$key" in
        QC_TOPOLOGY)
            printf '%s' "$val" | grep -qE "$VALID_TOPOLOGY" \
                || die "QC_TOPOLOGY must be A, B, C or D (got '$val')"
            topology="$val" ;;
        QC_BOARD_ACCESS)
            printf '%s' "$val" | grep -qE "$VALID_ACCESS" \
                || die "QC_BOARD_ACCESS must be one of: ssh-key ssh-password ssh-jump adb serial none (got '$val')"
            access="$val" ;;
        QC_BOARD_HOST) board="$val" ;;
        QC_BUILD_HOST) build="$val" ;;
        QC_HTP_ARCH)
            # Empty is fine and often correct. A value must look like an arch.
            [ -z "$val" ] || printf '%s' "$val" | grep -qE '^v[0-9]{2,3}$' \
                || die "QC_HTP_ARCH should be like 'v68', or empty if the board was not reachable (got '$val')" ;;
        QC_SETUP_VERSION) continue ;;   # we own this one
    esac
    LINES+=("$line")
done

[ -n "$topology" ] || die "QC_TOPOLOGY is required (A, B, C or D)"
[ -n "$access" ]   || die "QC_BOARD_ACCESS is required (use 'none' if there is no board yet)"

# --- consistency checks, as warnings: the user may know better ---
if [ "$access" != "none" ] && [ -z "$board" ]; then
    warn "QC_BOARD_ACCESS=$access but QC_BOARD_HOST is empty - board skills cannot run"
fi
if [ "$access" = "none" ] && [ -n "$board" ]; then
    warn "QC_BOARD_HOST is set but QC_BOARD_ACCESS=none - board will be treated as unavailable"
fi
if [ "$topology" != "D" ] && [ -z "$build" ]; then
    warn "QC_TOPOLOGY=$topology but QC_BUILD_HOST is empty - nothing can convert a model"
fi

# --- write atomically ---
{
    echo "# .qualcomm-env - generated by qualcomm-setup on $(date -Iseconds)"
    echo "# Values are READ from the machines, not assumed. Re-run qualcomm-setup to refresh."
    echo "# NEVER COMMIT - names internal hosts. No credentials are stored here by design."
    echo
    echo "QC_SETUP_VERSION=$SCHEMA"
    printf '%s\n' "${LINES[@]}"
} > "$TMP"

mv -f "$TMP" "$OUT"

# --- permissions: attempt, then VERIFY. Do not claim what did not happen. ---
chmod 600 "$OUT" 2>/dev/null || true
MODE=$(stat -c %a "$OUT" 2>/dev/null || stat -f %Lp "$OUT" 2>/dev/null || echo "?")
echo "wrote $OUT (mode $MODE)"

if [ "$MODE" != "600" ]; then
    warn "chmod 600 did not take (mode is $MODE).
         Windows and some mounted filesystems ignore POSIX permissions.
         This file is NOT protected by permissions - .gitignore is the only
         thing keeping it out of the repo. Verify that:"
    echo "           git check-ignore .qualcomm-env" >&2
fi

# --- gitignore ---
GI="$(dirname "$OUT")/.gitignore"
if [ -f "$GI" ] && ! grep -qxF '.qualcomm-env' "$GI"; then
    warn ".qualcomm-env is not listed in $GI - add it before committing anything"
elif [ ! -f "$GI" ]; then
    warn "no .gitignore beside $OUT - create one containing '.qualcomm-env'"
fi

echo
echo "Setup recorded. Other Qualcomm skills will read this and stop asking."
[ "$access" = "none" ] && echo "No board configured: board-dependent skills will say so rather than failing."
exit 0
